// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWK-Q61FDUv94_BPTHSr6RtSOmyIgMHNw',
    appId: '1:935646886754:web:8f7f58256859fdef274a3b',
    messagingSenderId: '935646886754',
    projectId: 'anidiary-2f59b',
    authDomain: 'anidiary-2f59b.firebaseapp.com',
    databaseURL: 'https://anidiary-2f59b-default-rtdb.firebaseio.com',
    storageBucket: 'anidiary-2f59b.appspot.com',
    measurementId: 'G-Z75EVD3VGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_1EPo99JKXV2ZxpKF3Xyv-24nmmSRLw',
    appId: '1:935646886754:android:8e39f4bcbbbca8a9274a3b',
    messagingSenderId: '935646886754',
    projectId: 'anidiary-2f59b',
    databaseURL: 'https://anidiary-2f59b-default-rtdb.firebaseio.com',
    storageBucket: 'anidiary-2f59b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhf-Q4wdy_Ap17uqTPS7FBpcZ3sM2P-fg',
    appId: '1:935646886754:ios:1a28dcf09d591dee274a3b',
    messagingSenderId: '935646886754',
    projectId: 'anidiary-2f59b',
    databaseURL: 'https://anidiary-2f59b-default-rtdb.firebaseio.com',
    storageBucket: 'anidiary-2f59b.appspot.com',
    iosClientId: '935646886754-musaj76vra9pqgbg9mre1uaktbjrrfjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.anidiaryRevised',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhf-Q4wdy_Ap17uqTPS7FBpcZ3sM2P-fg',
    appId: '1:935646886754:ios:1a28dcf09d591dee274a3b',
    messagingSenderId: '935646886754',
    projectId: 'anidiary-2f59b',
    databaseURL: 'https://anidiary-2f59b-default-rtdb.firebaseio.com',
    storageBucket: 'anidiary-2f59b.appspot.com',
    iosClientId: '935646886754-musaj76vra9pqgbg9mre1uaktbjrrfjj.apps.googleusercontent.com',
    iosBundleId: 'com.example.anidiaryRevised',
  );
}
